name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
      - main
  pull_request:
    branches:
      - '**'

jobs:

  test-build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Run unit tests
        run: |
          npm install
          npm test

      - name: Build Docker image
        run: |
          docker build -t dockerdys/springboot-app:main .

      - name: Build documentation
        run: |
          mvn javadoc:javadoc

  deploy:
    runs-on: ubuntu-latest
    needs: test-build-docs
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t dockerdys/springboot-app:main .
          docker push dockerdys/springboot-app:main

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cta300rtq21c73bv7egg/deploy \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Deploy documentation to Netlify
        run: |
          netlify deploy --prod --dir=.

  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add workflow status badge to README
        run: |
          echo "![CI/CD Status](https://img.shields.io/github/workflow/status/${{ github.repository }}/CI/CD%20Pipeline?label=CI%2FCD%20Status)" >> README.md
          git config --global user.name "Zaouich123"
          git config --global user.email "etienne.baillie@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with CI/CD status badge"
          git push origin main



